### ISSUE TITLE
Django 1.10 support - BaseCommand has no attribute 'option_list'

### ISSUE THREAD

**Issue by umbrae** [ChristopherRabotin/bungiesearch#163]
Looks like this was removed in 1.10, meaning creating search indexes is no longer working:

```
➜  src git:(master) ✗ python manage.py search_index --create
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  ...
  File "/Users/umbrae/.pyenv/versions/tmpproj/lib/python3.6/site-packages/bungiesearch/management/commands/search_index.py", line 16, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

Ref: https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#django.core.management.BaseCommand.option_list

**Comment by umbrae** [comment]
Whoops, noticed this is a duplicate of https://github.com/ChristopherRabotin/bungiesearch/pull/156 - closing.
